version: '1.0.0'
services:
  -api-two:
    build: ./docker-api-test-2
    ports: 
      - 5002:5002
    environment:
      ASPNETCORE_ENVIORNMENT: 'Development'
      ASPNETCORE_URLS: http://+:5002

  -api-one:
    build: ./docker-api-test
    ports: 
      - 5001:5001
    environment:
      ASPNETCORE_ENVIORNMENT: 'Production'
      ASPNETCORE_URLS: http://+:5001
  
