name: .NET

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Build dockerfile api-test-2
      run: docker build -t docker/dotnet-api-test-2 .
      working-directory: docker-api-test-2 

    - name: Test api-2
      run: dotnet test 
      working-directory: docker-api-test-2 


    - name: Upload image 2
      uses: ishworkh/docker-image-artifact-upload@v2.0.1
      with:
        image: "docker/dotnet-api-test-2:latest"
  
  deploy:
    needs: build
    environment: dev
    runs-on: 
      - self-hosted
    
    steps:
      - name: Downlowad docker image
        uses: ishworkh/container-image-artifact-download@v1.0.0
        with:
          image: "docker/dotnet-api-test-2:latest"

      - name: Secret echo
        run: echo  ${{ secrets.super_secret_test }}

      - name: Run container
        run: docker run -d -p 5002:5002 docker/dotnet-api-test-2:latest
