# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3
      
    - name: Build dockerfile api-test-1
      run: docker build -t docker/dotnet-api-test .
      working-directory: docker-api-test 
      
    - name: Build dockerfile api-test-2
      run: docker build -t docker/dotnet-api-test-2 .
      working-directory: docker-api-test-2 
